<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <?php
        // put your code here
        class Car {
    function Car() {
        $this->model = "Q7";
    }
}

// create an object
$Audi = new Car();

// show object properties
echo $Audi->model;
        ?>
    </body>
</html>
